# -*- coding: utf-8 -*-
"""portfolio_allocator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xanORi-eXgbkFqeqLwJbmPzJ0aet9l-Z

#**Portfolio Allocation Using Python**

##**Data Collection and importing libraries.**
"""

import requests
import pandas as pd
from datetime import date
from datetime import datetime
from datetime import timedelta
from dateutil.relativedelta import *


"""import yfinance as yf

def get_price_history(symbols: list[str], start_date: str, end_date: str) -> pd.DataFrame:

   ## Downloads historical stock prices from Yahoo Finance for multiple symbols
    ##and returns them in a single long-format DataFrame.


    all_dfs = []

    for symbol in symbols:
        print(f"Downloading data for {symbol}...")
        df = yf.download(symbol,
                         start=start_date,
                         end=end_date,
                         auto_adjust=True, # Auto-adjust for splits and dividends
                         progress=False)

        if not df.empty:
            # Keep only 'Close' (which is adjusted close due to auto_adjust=True)
            # and rename to 'close' to match later pivot operation
            df_filtered = df[['Close']].copy()
            df_filtered.columns = ['close']
            df_filtered['symbol'] = symbol
            df_filtered['date'] = df_filtered.index # Make 'Date' a column
            df_filtered.reset_index(drop=True, inplace=True) # Reset index to be default integer index
            all_dfs.append(df_filtered)
            print(df_filtered.head())
        else:
            print(f"No data downloaded for {symbol}.")

        print("-" * 60)

    if all_dfs:
        combined_df = pd.concat(all_dfs, ignore_index=True)
        return combined_df
    else:
        return pd.DataFrame(columns=['date', 'symbol', 'close'])"""

import pathlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.optimize as sci_opt

from pprint import pprint
from sklearn.preprocessing import StandardScaler

# Set some display options for Pandas.
pd.set_option('display.max_colwidth',None) #changed -1 to none
pd.set_option('expand_frame_repr', False)

import pathlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.optimize as sci_opt

from pprint import pprint
from sklearn.preprocessing import StandardScaler
from datetime import datetime # Ensure datetime is imported for direct use

"""# Set some display options for Pandas.
pd.set_option('display.max_colwidth',None)
pd.set_option('expand_frame_repr', False)

# Define the symbols
symbols = ['HDFCBANK.NS','TCS.NS' , 'ICICIBANK.NS' , 'SBIN.NS' , 'INFY.NS' ,
           'BHARTIARTL.NS' , 'RELIANCE.NS' , 'TATAMOTORS.NS' , 'M&M.NS' , 'HINDUNILVR.NS',
           'ITC.NS','SUNPHARMA.NS' , 'DRREDDY.NS' , 'LT.NS' , 'BAJFINANCE.NS','SBILIFE.NS',
           'ULTRACEMCO.NS','TITAN.NS','NTPC.NS','BEL.NS']   #20 Stocks from diverse industries

# At different points, we will need to generate metrics based on the number
# of symbols we have, so let's save some time and just calculate that now.
number_of_symbols = len(symbols)

# Ensure the 'data' directory exists
data_dir = pathlib.Path('data')
data_dir.mkdir(parents=True, exist_ok=True)
csv_file_path = data_dir / 'stock_data_1.csv'

# If we don't have data then grab it
if not csv_file_path.exists():

    # Call get_price_history, which now returns a DataFrame directly.
    price_data_frame = get_price_history(symbols=symbols ,start_date = '2022-05-20', end_date = '2026-06-30') #date has been changed to a fixed date because it is difficult to process yfinance libraries in streamlit.

    # Dump it to a CSV file.
    price_data_frame.to_csv(
        csv_file_path,
        index=False
    )
    print("Saved data to stock_data_1.csv")

else:

    # Load the data.
    price_data_frame: pd.DataFrame = pd.read_csv(csv_file_path)

# Print the head.
print(price_data_frame.head())"""  #some code has been commented out because we do not want to do function calls from yfinance again and again as that takes a lot of time during deployment.
                                    #originally , the dataset was obtained from yfinance itself.

price_data_frame = pd.read_csv('stock_data_1.csv')

"""####*It will be convenient for us to see the target variable(close price) at the end , so let us rearrange the columns of this dataframe.*"""

# don't need all columns so we will store only useful columns
price_data_frame = price_data_frame[['date', 'symbol', 'close']]

#arranging the data around date
price_data_frame = price_data_frame.pivot(
    index='date',
    columns='symbol',
    values='close'
)
price_data_frame

price_data_frame.shape

"""###**The Task At Hand**

Our job as a portfolio manager is to make the 'best possible portfolio' for our clients.But what is best possible portfolio?For some clients , it might be one that maximises return at whatever it takes.For some , it might be minimizing risk while keeping returns stable.For some , it might be a mixture of both , it just depends on the client's risk appetite.Eventually , clients end up wanting a good risk-adjusted return.One metric that we use to judge this is Sharpe Ratio , whose formula is. as:

\begin{equation*}
\text{Sharpe Ratio} = \frac{(R_p - R_f)}{\sigma_p}
\end{equation*}

Where:

$
\begin{align}
\ R_p & = \text{Return of Portfolio} \\
\ R_f & = \text{Risk-Free Rate} \\
\ \sigma_p & = \text{Standard Deviation of Portfolio's Excess Return} \\
\end{align}
$

To calculate the expected returns, we use the following formula:

\begin{equation*}
\ R_p = (w_{1}r_{1}) + (w_{2}r_{2}) + \cdots + (w_{n}r_{n})
\end{equation*}

Where:

$
\begin{align}
\ r_{i} & = \text{Return of Security i} \\
\ w_{i} & = \text{Weight of Security i} \\
\end{align}
$

To calculate the standard deviation of the protfolio, we use the following formula:

\begin{equation*}
\ \sigma_p = \sqrt{(w_{i}^2 \sigma_i^2) + (w_{j}^2 \sigma_j^2) + (2w_{j}w_{i} p_{i,j} \sigma_i \sigma_j)}
\end{equation*}

Where:

$
\begin{align}
\ \sigma_{i} & = \text{Standard Deviation of Returns for Security i} \\
\ w_{i} & = \text{Weight of Security i} \\
\ p_{i,j} & = \text{Correlation Coefficent between the returns of asset i and asset j} \\
\end{align}
$

###**Any sharpe ratio under 1 is not good , over 1 it gets better** ###improve pls

###**General Situation Before Applying any Optimization Techniques**
"""

# 1. Calculate log returns
log_return = np.log(1 + price_data_frame.pct_change())

# 2. Generate random weights
random_weights = np.array(np.random.random(number_of_symbols-1)) #one stock's data couldnt get downloaded
rebalance_weights = random_weights / np.sum(random_weights)

# 3.Calculating expected return for the year (multiplying by 252 because there are approx. 252 trading days in the market)
exp_ret = np.sum((log_return.mean() * rebalance_weights) * 252)

# 4. Calculating expected volatility and annualizing it
exp_vol = np.sqrt(
np.dot(
    rebalance_weights.T,
    np.dot(
        log_return.cov() * 252,
        rebalance_weights
    )
)
)

# 5. Calculate Sharpe Ratio.
sharpe_ratio = (exp_ret -0.01)/ exp_vol  #assuming risk free rate to be 1%

# Put the weights into a data frame.
weights_df = pd.DataFrame(data={
'random_weights': random_weights,
'rebalance_weights': rebalance_weights
})
print('')
print('='*80)
print('PORTFOLIO WEIGHTS:')
print('-'*80)
print(weights_df)
print('-'*80)

# Do the same with the other metrics.
metrics_df = pd.DataFrame(data={
    'Expected Portfolio Returns': exp_ret,
    'Expected Portfolio Volatility': exp_vol,
    'Portfolio Sharpe Ratio': sharpe_ratio
}, index=[0])

print('')
print('='*80)
print('PORTFOLIO METRICS:')
print('-'*80)
print(metrics_df)
print('-'*80)

log_return = np.log(1 + price_data_frame.pct_change())
log_return.mean()

"""##**Portfolio Optimization Technique 1: Monte Carlo Simulations**

Monte Carlo simulations are used to model the probability of different outcomes in a process that cannot easily be predicted due to the intervention of random variables. It is a technique used to understand the impact of risk and uncertainty in prediction and forecasting models.

What we can do is this.We could test a bunch of different random allocations and see which ones produces the highest Sharpe Ratio.If we run enough random allocations , we might just stumble upon the best one.Why?

Random sampling and the law of large numbers is what enables us to find the best possible allocation.
"""

# Initializing...

# We will run 100000 iterations.
num_of_portfolios = 100000

# Prep an array to store the weights as they are generated, 5000 iterations for each of our 4 symbols.
all_weights = np.zeros((num_of_portfolios, number_of_symbols-1))

# Prep an array to store the returns as they are generated, 5000 possible return values.
ret_arr = np.zeros(num_of_portfolios)

# Prep an array to store the volatilities as they are generated, 5000 possible volatility values.
vol_arr = np.zeros(num_of_portfolios)

# Prep an array to store the sharpe ratios as they are generated, 5000 possible Sharpe Ratios.
sharpe_arr = np.zeros(num_of_portfolios)

# Start the simulations.
for ind in range(num_of_portfolios):

    # First, calculate the weights.
    weights = np.array(np.random.random(number_of_symbols-1))
    weights = weights / np.sum(weights)

    # Add the weights, to the `weights_arrays`.
    all_weights[ind, :] = weights

    # Calculate the expected log returns, and add them to the `returns_array`.
    ret_arr[ind] = np.sum((log_return.mean() * weights) * 252)   ##multplying by 252 to "annualize returns"

    # Calculate the volatility, and add them to the `volatility_array`.
    vol_arr[ind] = np.sqrt(
        np.dot(weights.T, np.dot(log_return.cov() * 252, weights))
    )

    # Calculate the Sharpe Ratio and Add it to the `sharpe_ratio_array`.
    sharpe_arr[ind] = ret_arr[ind]/vol_arr[ind]

# Let's create our "Master Data Frame", with the weights, the returns, the volatility, and the Sharpe Ratio
simulations_data = [ret_arr, vol_arr, sharpe_arr, all_weights]

# Create a DataFrame from it, then Transpose it so it looks like our original one.
simulations_df = pd.DataFrame(data=simulations_data).T

# Give the columns the Proper Names.
simulations_df.columns = [
    'Returns',
    'Volatility',
    'Sharpe Ratio',
    'Portfolio Weights'
]

# Make sure the data types are correct, we don't want our floats to be strings.
simulations_df = simulations_df.infer_objects()

# Print out the results.
print('')
print('='*80)
print('SIMULATIONS RESULT:')
print('-'*80)
display(simulations_df.head(15))
print('-'*80)

"""##**Getting the Important Metrics**

After running our simulation let's take a look at some interesting metrics. It will be beneficial to our clients to know what allocation gves the maximum sharpe ratio and what allocation gives the minumum volatility.
"""

# Return the Max Sharpe Ratio from the run.
max_sharpe_ratio = simulations_df.loc[simulations_df['Sharpe Ratio'].idxmax()]

# Return the Min Volatility from the run.
min_volatility = simulations_df.loc[simulations_df['Volatility'].idxmin()]

print('')
print('='*80)
print('MAX SHARPE RATIO:')
print('-'*80)
print(max_sharpe_ratio)
print('-'*80)

print('')
print('='*80)
print('MIN VOLATILITY:')
print('-'*80)
print(min_volatility)
print('-'*80)

"""##**Plotting**"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

# Plot the data on a Scatter plot.
plt.scatter(
    y=simulations_df['Returns'],
    x=simulations_df['Volatility'],
    c=simulations_df['Sharpe Ratio'],
    cmap='RdYlBu'
)

# Give the Plot some labels, and titles.
plt.title('Portfolio Returns Vs. Risk')
plt.colorbar(label='Sharpe Ratio')
plt.xlabel('Standard Deviation')
plt.ylabel('Returns')

# Plot the Max Sharpe Ratio, using a `Red Star`.
plt.scatter(
    max_sharpe_ratio[1],
    max_sharpe_ratio[0],
    marker=(5, 1, 0),
    color='r',
    s=600
)

# Plot the Min Volatility, using a `Blue Star`.
plt.scatter(
    min_volatility[1],
    min_volatility[0],
    marker=(5, 1, 0),
    color='b',
    s=600
)

# Finally, show the plot.
plt.show()

"""##**Some Useful Functions**"""

def get_metrics(weights: list) -> np.array:
    """
    With a given set of weights, return the portfolio returns,
    the portfolio volatility, and the portfolio sharpe ratio.
    """

    # Converting to a Numpy Array.
    weights = np.array(weights)

    # Calculating the returns and annualize them
    ret = np.sum(log_return.mean() * weights) * 252

    # Calculate the volatility and annualize them
    vol = np.sqrt(
        np.dot(
            weights.T,
            np.dot(
                log_return.cov() * 252,
                weights
            )
        )
    )

    # Calculate the Sharpe Ratio.
    sr = ret / vol

    return np.array([ret, vol, sr])

def grab_negative_sharpe(weights: list) -> np.array:
    """The function used to maximise the Sharpe Ratio.
    """
    # To maximize Sharpe Ratio using a minimizer, return the negative Sharpe Ratio
    return -get_metrics(weights)[2]

def grab_volatility(weights: list) -> np.array:
    """The function used to minimize the Volatility.
    """
    return get_metrics(weights)[1]

def check_sum(weights: list) -> float:
    """Ensure the allocations of the weights, sums to 1
    """
    return np.sum(weights) - 1

"""##**Portfolio Optimization Technique -2 : Sequential Least Squares Programming**

Sequential Least Squares Programming (SLSQP) is a gradient-based optimization algorithm used to solve nonlinear optimization problems with constraints. It is widely used in portfolio optimization because it can handle equality constraints, inequality constraints, and variable bounds simultaneously.

At each iteration, SLSQP approximates the original nonlinear optimization problem with a simpler quadratic programming subproblem. It then solves this subproblem, updates the solution, and repeats the process until convergence. This iterative approach makes the algorithm efficient for many practical optimization problems.

In portfolio optimization, SLSQP is commonly used to maximize the Sharpe ratio or minimize portfolio risk while satisfying constraints such as:

- The sum of portfolio weights equals 1
- No short selling (weights ≥ 0).
- Maximum allocation limits for individual assets.

### **Advantages**
- Handles both equality and inequality constraints.
- Supports upper and lower bounds on variables.
- Efficient for small to medium-sized optimization problems.
- Widely available through SciPy's `minimize()` function.

### **Limitations**
- Requires the objective function to be smooth and differentiable.
- Finds a local optimum, which may not always be the global optimum.
- Performance can depend on the initial starting solution.

SLSQP is one of the most commonly used optimization algorithms in quantitative finance and is well suited for constructing optimal portfolios using the Markowitz Mean-Variance framework, Maximum Sharpe Ratio optimization, and Minimum Variance portfolio optimization.
"""

# Define the boundaries for each symbol. Remember I can only invest up to 100% of my capital into a single asset.
bounds = tuple((0, 1) for symbol in range(number_of_symbols-1))

# Define the constraints, here I'm saying that the sum of each weight must not exceed 100%.
constraints = ({'type': 'eq', 'fun': check_sum})

# We need to create an initial guess to start with,
# and usually the best initial guess is just an
# even distribution.
init_guess = (number_of_symbols-1) * [1 / (number_of_symbols-1)]

# Perform the operation to minimize the risk.
optimized_sharpe = sci_opt.minimize(
    grab_negative_sharpe, # minimize this.
    init_guess, # Start with these values.
    method='SLSQP',
    bounds=bounds, # don't exceed these bounds.
    constraints=constraints # make sure you don't exceed the 100% constraint.
)

# Print the results.
print('')
print('='*80)
print('OPTIMIZED SHARPE RATIO:')
print('-'*80)
print(optimized_sharpe)
print('-'*80)   ##you can optimise for minimum volatility or for return also , -food for future work

# Getting the metrics
optimized_metrics = get_metrics(weights=optimized_sharpe.x)

# Getting the Optimized Weights.
print('')
print('='*80)
print('OPTIMIZED WEIGHTS:')
print('-'*80)
print(optimized_sharpe.x)
print('-'*80)


# Getting the Optimized Metrics.
print('')
print('='*80)
print('OPTIMIZED METRICS:')
print('-'*80)
print(optimized_metrics)
print('-'*80)

# Let us define the boundaries for each symbol.
bounds = tuple((0, 1) for symbol in range(number_of_symbols-1))

# We define  the constraints, by stating that the sum of all weights must not exceed 100%.
constraints = ({'type': 'eq', 'fun': check_sum})

# We need to create an initial guess to start with,
# and usually the best initial guess is just an
# even distribution. In this case 25% for each of the 4 stocks.
init_guess = (number_of_symbols-1) * [1 / (number_of_symbols-1)]

# Perform the operation to minimize the risk.
optimized_volatility = sci_opt.minimize(
    grab_volatility, # minimize this.
    init_guess, # Start with these values.
    method='SLSQP',
    bounds=bounds, # don't exceed these bounds.
    constraints=constraints # make sure you don't exceed the 100% constraint.
)

# Print the results.
print('')
print('='*80)
print('OPTIMIZED VOLATILITY RATIO:')
print('-'*80)
print(optimized_volatility)
print('-'*80)

# Grab the metrics.
optimized_metrics = get_metrics(weights=optimized_volatility.x)

# Print the Optimized Weights.
print('')
print('='*80)
print('OPTIMIZED WEIGHTS:')
print('-'*80)
print(optimized_volatility.x)
print('-'*80)


# Print the Optimized Metrics.
print('')
print('='*80)
print('OPTIMIZED METRICS:')
print('-'*80)
print(optimized_metrics)
print('-'*80)

"""##**Conclusion**

We started our journey by downloading data of some stocks from yfinance.Eventually , we ran some Monte Carlo simulations and performed an optimization technique(SLSQP) to get the 'best' possible allocation for our clients.The goodness of our allocation was judged using Sharpe Ratio.We also testes to minimize the volatility of our portfolio as a separate part of the project.

*   **Sharpe Ratio From Monte Carlo** - 0.65978
*   **Sharpe Ratio From SLSQP** - 0.62375

"""

